### ISSUE TITLE
react-native-universal

### ISSUE THREAD

**Issue by ross-rosario** [tuckerconnelly/react-native-match-media#1]
I'm planning on using Uranium to accomplish a responsive UI, both for web and native. It seems that react-native-match-media is required for Uranium to work in RN, and that the former has a dependency on react-native-universal.

I'm wondering if react-native-universal is still necessary. I'm under the impression that carbon-ui is honoring webpack react-native aliasing rather than react-native-universal.

If indeed react-native-universal is no longer required, what would be the steps to eject it from react-native-match-media?

Thanks!

**Comment by ross-rosario** [comment]
Also, please let me know if this should be addressed in Uranium instead.

**Comment by tuckerconnelly** [comment]
Hey yeah, trying to move away from react-native-universal :) Aliasing is the way to go imo

**Comment by tuckerconnelly** [comment]
Don't really have time to play with it now, but would accept a PR to switch it to react-native. I _think_ it should just work.

**Comment by ross-rosario** [comment]
It does work with just an aliased react-native-web :). PR is in #2
